version: '2.0'
services:
   jd-v4:
      image: nevinee/jd:v4
      container_name: jd
      restart: always
      tty: true
      volumes:
         - ./config:/jd/config
         - ./log:/jd/log
         - ./own:/jd/own
      ports:
         - 5678:5678
      environment:
         - ENABLE_HANGUP: false
